### PR TITLE
fix: rename file to fix compilation errors

### PR DESCRIPTION
**Pull request by Gary-Hobson**
I failed to compile with master branch on ubuntu 20.04 (X86-64)

It seems to be caused by some letter case differences

### CODE REVIEW

**Comment by kisvegabor** [comment]
cc @Sxs7513

**Review by haigithub — COMMENTED** [review]
I had a similar problem when building on Linux environment(Ubuntu 20.04). 

**I also modifyed below source files:**  (for reference only)
src/render/native/components/calendar/calendar_wrap.cpp
src/render/native/components/gif/gif_wrap.cpp
src/render/native/components/mask/mask_wrap.cpp
src/render/CMakeLists.txt

**git diff src/render/native/components/calendar/calendar_wrap.cpp**
diff --git a/src/render/native/components/calendar/calendar_wrap.cpp b/src/render/native/components/calendar/calendar_wrap.cpp
index 1177525..e8283cb 100644
--- a/src/render/native/components/calendar/calendar_wrap.cpp
+++ b/src/render/native/components/calendar/calendar_wrap.cpp
@@ -1,4 +1,4 @@
-#include "Calendar.hpp"
+#include "calendar.hpp"
 
 static JSClassID CalendarClassID;


**git diff src/render/native/components/gif/gif_wrap.cpp**
diff --git a/src/render/native/components/gif/gif_wrap.cpp b/src/render/native/components/gif/gif_wrap.cpp
index ee920ba..1f44e90 100644
--- a/src/render/native/components/gif/gif_wrap.cpp
+++ b/src/render/native/components/gif/gif_wrap.cpp
@@ -1,4 +1,4 @@
-#include "GIF.hpp"
+#include "gif.hpp"
 
 static JSClassID GIFClassID;


**git diff src/render/native/components/mask/mask_wrap.cpp**
diff --git a/src/render/native/components/mask/mask_wrap.cpp b/src/render/native/components/mask/mask_wrap.cpp
index 5d7ccd8..36cd726 100644
--- a/src/render/native/components/mask/mask_wrap.cpp
+++ b/src/render/native/components/mask/mask_wrap.cpp
@@ -1,4 +1,4 @@
-#include "Mask.hpp"
+#include "mask.hpp"
 
 static JSClassID MaskClassID;

**git diff src/render/CMakeLists.txt**
src_render_CMakeLists txt

**Other difference about package.json and package-lock.json**
(for reference only. different with this patch, maybe build env )
**git diff package.json**
package json

**git diff package-lock.json**
package-lock json

**Comment by zdzDesigner** [comment]
same as:

diff --git a/src/render/native/components/calendar/calendar_wrap.cpp b/src/render/native/components/calendar/calendar_wrap.cpp
index 1177525..e8283cb 100644
--- a/src/render/native/components/calendar/calendar_wrap.cpp
+++ b/src/render/native/components/calendar/calendar_wrap.cpp
@@ -1,4 +1,4 @@
-#include "Calendar.hpp"
+#include "calendar.hpp"

 static JSClassID CalendarClassID;

diff --git a/src/render/native/components/gif/gif_wrap.cpp b/src/render/native/components/gif/gif_wrap.cpp
index ee920ba..1f44e90 100644
--- a/src/render/native/components/gif/gif_wrap.cpp
+++ b/src/render/native/components/gif/gif_wrap.cpp
@@ -1,4 +1,4 @@
-#include "GIF.hpp"
+#include "gif.hpp"

 static JSClassID GIFClassID;

diff --git a/src/render/native/components/mask/mask_wrap.cpp b/src/render/native/components/mask/mask_wrap.cpp
index 5d7ccd8..36cd726 100644
--- a/src/render/native/components/mask/mask_wrap.cpp
+++ b/src/render/native/components/mask/mask_wrap.cpp
@@ -1,4 +1,4 @@
-#include "Mask.hpp"
+#include "mask.hpp"

 static JSClassID MaskClassID;

**Comment by svits-llc** [comment]
Hi! Is this one not merged? What ius the workaround then? We hit the same issue.

**Comment by Gary-Hobson** [comment]
@kisvegabor This PR has not received a reply for too long. I thought no one maintained this repository, so I closed it.

Fortunately it seems to be active now, but the problem still exists

**Comment by kisvegabor** [comment]
Hey,

Actually, @derekstavis is maintaining this repository now. Derek, could you take look as this pull request?

**Comment by derekstavis** [comment]
I'll look into this in the next few days. I didn't have notifications enabled in the repo and missed all the updates :sweat_smile:

**Comment by derekstavis** [comment]
Please let me know if this is still a problem in the latest main
